const bands = [

{name:"KOTORI",tags:["emo","livehouse","lyrics","youth"]},
{name:"Fish and Lips",tags:["indie","livehouse","youth"]},
{name:"the paddles",tags:["indie","guitar","livehouse"]},
{name:"Blue Mash",tags:["indie","guitar"]},
{name:"猫背のネイビーセゾン",tags:["indie","melody"]},
{name:"帝国喫茶",tags:["indie","shimokitazawa","melody"]},
{name:"ルサンチマン",tags:["alternative","lyrics"]},
{name:"時速36km",tags:["indie","lyrics","livehouse"]},
{name:"Sunny Girl",tags:["indie","melody","youth"]},
{name:"アルステイク",tags:["indie","livehouse"]},

{name:"Arakezuri",tags:["indie","livehouse"]},
{name:"Brown Basket",tags:["punk","livehouse"]},
{name:"ammo",tags:["punk","livehouse","lyrics"]},
{name:"Maki",tags:["emo","livehouse"]},
{name:"kobore",tags:["punk","melody"]},
{name:"KALMA",tags:["punk","youth"]},
{name:"HERO COMPLEX",tags:["punk"]},
{name:"プッシュプルポット",tags:["punk","livehouse"]},
{name:"TETORA",tags:["punk","femalevo","livehouse"]},
{name:"Hump Back",tags:["punk","femalevo","livehouse"]},

{name:"Hakubi",tags:["emo","femalevo","lyrics"]},
{name:"climbgrow",tags:["rock","livehouse"]},
{name:"さよならポエジー",tags:["emo","lyrics"]},
{name:"cinema staff",tags:["emo","alternative"]},
{name:"Age Factory",tags:["alternative","livehouse"]},
{name:"SIX LOUNGE",tags:["rock","loud"]},
{name:"THE ORAL CIGARETTES",tags:["loud","fes"]},
{name:"coldrain",tags:["loud"]},
{name:"SiM",tags:["loud","fes"]},
{name:"Crossfaith",tags:["loud"]},

{name:"Crystal Lake",tags:["loud"]},
{name:"SHADOWS",tags:["loud"]},
{name:"NOISEMAKER",tags:["loud"]},
{name:"Survive Said The Prophet",tags:["loud"]},
{name:"ROTTENGRAFFTY",tags:["loud","fes"]},
{name:"Fear, and Loathing in Las Vegas",tags:["loud"]},
{name:"9mm Parabellum Bullet",tags:["loud"]},
{name:"凛として時雨",tags:["alternative"]},
{name:"TK from 凛として時雨",tags:["alternative"]},
{name:"THE NOVEMBERS",tags:["shoegaze"]},

{name:"ART-SCHOOL",tags:["shoegaze"]},
{name:"downy",tags:["postrock"]},
{name:"envy",tags:["screamo"]},
{name:"04 Limited Sazabys",tags:["punk","melocore","fes"]},
{name:"HEY-SMITH",tags:["punk","melocore","fes"]},
{name:"SHANK",tags:["punk","melocore"]},
{name:"ENTH",tags:["punk","melocore"]},
{name:"dustbox",tags:["punk","melocore"]},
{name:"locofrank",tags:["punk","melocore"]},
{name:"Hawaiian6",tags:["punk","melocore"]},

{name:"TOTALFAT",tags:["punk","melocore"]},
{name:"Northern19",tags:["punk","melocore"]},
{name:"GOOD4NOTHING",tags:["punk","melocore"]},
{name:"WANIMA",tags:["punk","melocore","fes"]},
{name:"10-FEET",tags:["punk","melocore","fes"]},
{name:"ELLEGARDEN",tags:["punk","melocore","fes"]},
{name:"MONOEYES",tags:["punk","melocore"]},
{name:"KUZIRA",tags:["punk","melocore"]},
{name:"SABANNAMAN",tags:["punk"]},
{name:"OVER ARM THROW",tags:["punk"]},

{name:"STOMPIN' BIRD",tags:["punk"]},
{name:"THE STARBEMS",tags:["punk"]},
{name:"STANCE PUNKS",tags:["punk"]},
{name:"Saucy Dog",tags:["melody","lyrics","fes"]},
{name:"マカロニえんぴつ",tags:["melody","fes"]},
{name:"sumika",tags:["melody","fes"]},
{name:"KEYTALK",tags:["guitar","fes"]},
{name:"go!go!vanillas",tags:["guitar","fes"]},
{name:"KANA-BOON",tags:["guitar","fes"]},
{name:"フレデリック",tags:["alternative","fes"]},

{name:"ヤバイTシャツ屋さん",tags:["punk","fes"]},
{name:"キュウソネコカミ",tags:["fes"]},
{name:"打首獄門同好会",tags:["fes"]},
{name:"四星球",tags:["fes"]},
{name:"バックドロップシンデレラ",tags:["fes"]},
{name:"セックスマシーン!!",tags:["fes"]},
{name:"夜の本気ダンス",tags:["dance"]},
{name:"Lucky Kilimanjaro",tags:["dance"]},
{name:"Awesome City Club",tags:["pop"]},
{name:"Suchmos",tags:["groove"]},

{name:"Nulbarich",tags:["groove"]},
{name:"King Gnu",tags:["alternative","fes"]},
{name:"サカナクション",tags:["alternative","fes"]},
{name:"BUMP OF CHICKEN",tags:["melody","lyrics"]},
{name:"ASIAN KUNG-FU GENERATION",tags:["guitar","fes"]},
{name:"RADWIMPS",tags:["lyrics"]},
{name:"Mr.Children",tags:["melody"]},
{name:"スピッツ",tags:["melody"]},
{name:"くるり",tags:["rock"]},
{name:"Base Ball Bear",tags:["guitar"]},

{name:"UNISON SQUARE GARDEN",tags:["guitar"]},
{name:"THE BACK HORN",tags:["loud"]},
{name:"ストレイテナー",tags:["alternative"]},
{name:"Nothing's Carved In Stone",tags:["alternative"]},
{name:"ACIDMAN",tags:["alternative"]},
{name:"the HIATUS",tags:["alternative"]},
{name:"GLAY",tags:["rock"]},
{name:"L'Arc〜en〜Ciel",tags:["rock"]},
{name:"UVERworld",tags:["loud"]},
{name:"ONE OK ROCK",tags:["loud"]},

{name:"MAN WITH A MISSION",tags:["fes"]},
{name:"[Alexandros]",tags:["rock","fes"]},
{name:"back number",tags:["lyrics"]},
{name:"ナードマグネット",tags:["indie","guitar"]},
{name:"TENDOUJI",tags:["indie"]},
{name:"Lucie,Too",tags:["femalevo","indie"]},
{name:"MONO NO AWARE",tags:["indie"]},
{name:"PEOPLE 1",tags:["alternative"]},
{name:"NEE",tags:["alternative"]},
{name:"ドミコ",tags:["alternative"]},

{name:"ミツメ",tags:["indie"]},
{name:"never young beach",tags:["indie"]},
{name:"Laura day romance",tags:["indie"]},
{name:"The Wisely Brothers",tags:["femalevo","indie"]},
{name:"For Tracy Hyde",tags:["shoegaze"]},
{name:"宇宙ネコ子",tags:["shoegaze"]},
{name:"クレナズム",tags:["shoegaze"]},
{name:"きのこ帝国",tags:["shoegaze"]},
{name:"plenty",tags:["lyrics"]},
{name:"くだらない1日",tags:["indie"]}

]